name: Build and Deploy to GitHub Pages

# Run on pushes to main (change branch if your default branch is different)
on:
  push:
    branches:
      - main

permissions:
  contents: read        # for checkout
  pages: write          # to publish to GitHub Pages
  id-token: write       # required by deploy-pages action

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'    # choose LTS you prefer

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      # Upload the build output (dist) as the pages artifact
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Downloads the artifact uploaded by the build job
      - name: Download artifact
        uses: actions/download-pages-artifact@v1

      # Deploy to GitHub Pages (official action)
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
